baseurl = "https://girls.js.org/"
languageCode = "en-us"
title = "girls.js"
publishdir = "build"
theme = "hugo-strata-theme"

[params]
  custom_css = ['css/custom.css']


[params.sidebar]
  avatar = "girlsjs.svg"
  bio = "**girls.js**, a JavaScript community for girls, <br> truly created by girls"
  copyright = [
    "&copy; girls.js",
    "Design: [HTML5 UP](//html5up.net)",
    "[JS.org](//js.org)",
  ]

[params.about]
    hide  = false
    title = "About girls.js"
    content = "girls.js aims to inspire girls to jump into tech in a friendly and comfortable environment dedicated to girls. We help and organize 1-day workshops just for girls (sorry guys, you've already have a big community) in hopes of making technology more approachable and comfy for us."
